### ISSUE TITLE
Failure to boot should cause the bot to exit

### ISSUE THREAD

**Issue by dblock** [dblock/slack-ruby-bot#15]
```
2015-08-21T14:26:17.365071+00:00 app[web.1]: * Listening on tcp://0.0.0.0:5023
2015-08-21T14:26:17.450818+00:00 app[web.1]: I, [2015-08-21T14:26:17.450607 #3]  INFO -- : Welcome 'pongbot' to the 'Artsy' team at https://artsy.slack.com/.
2015-08-21T14:26:17.371591+00:00 app[web.1]: Use Ctrl-C to stop
2015-08-21T14:26:17.945314+00:00 app[web.1]: I, [2015-08-21T14:26:17.945185 #3]  INFO -- : Successfully connected to https://artsy.slack.com/.
2015-08-21T17:03:43.354298+00:00 app[web.1]: failed to read response string
2015-08-21T17:03:43.354376+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/faraday-0.9.1/lib/faraday/response.rb:9:in `block in call'
2015-08-21T17:03:43.354368+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/slack-ruby-client-0.2.1/lib/slack/web/faraday/response/raise_error.rb:8:in `on_complete'
2015-08-21T17:03:43.354377+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/faraday-0.9.1/lib/faraday/response.rb:57:in `on_complete'
2015-08-21T17:03:43.354381+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/faraday-0.9.1/lib/faraday/response.rb:8:in `call'
2015-08-21T17:03:43.354382+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/faraday-0.9.1/lib/faraday/response.rb:8:in `call'
2015-08-21T17:03:43.354386+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/faraday-0.9.1/lib/faraday/request/url_encoded.rb:15:in `call'
2015-08-21T17:03:43.354390+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/faraday-0.9.1/lib/faraday/request/multipart.rb:14:in `call'
2015-08-21T17:03:43.354395+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/faraday-0.9.1/lib/faraday/rack_builder.rb:139:in `build_response'
2015-08-21T17:03:43.354404+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/faraday-0.9.1/lib/faraday/connection.rb:177:in `post'
2015-08-21T17:03:43.354399+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/faraday-0.9.1/lib/faraday/connection.rb:377:in `run_request'
2015-08-21T17:03:43.354409+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/slack-ruby-client-0.2.1/lib/slack/web/faraday/request.rb:25:in `request'
2015-08-21T17:03:43.354412+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/slack-ruby-client-0.2.1/lib/slack/web/faraday/request.rb:10:in `post'
2015-08-21T17:03:43.354418+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/slack-ruby-client-0.2.1/lib/slack/web/api/endpoints/rtm.rb:15:in `rtm_start'
2015-08-21T17:03:43.354427+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/slack-ruby-client-0.2.1/lib/slack/real_time/client.rb:39:in `block in start!'
2015-08-21T17:03:43.354433+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/eventmachine-1.0.8/lib/eventmachine.rb:193:in `run_machine'
2015-08-21T17:03:43.354432+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/eventmachine-1.0.8/lib/eventmachine.rb:193:in `call'
2015-08-21T17:03:43.354437+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/eventmachine-1.0.8/lib/eventmachine.rb:193:in `run'
2015-08-21T17:03:43.354440+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/slack-ruby-client-0.2.1/lib/slack/real_time/client.rb:38:in `start!'
2015-08-21T17:03:43.354445+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/slack-ruby-bot-0.4.2/lib/slack-ruby-bot/app.rb:46:in `block in start!'
2015-08-21T17:03:43.354449+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/slack-ruby-bot-0.4.2/lib/slack-ruby-bot/app.rb:45:in `loop'
2015-08-21T17:03:43.354454+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/slack-ruby-bot-0.4.2/lib/slack-ruby-bot/app.rb:45:in `start!'
2015-08-21T17:03:43.354458+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/slack-ruby-bot-0.4.2/lib/slack-ruby-bot/app.rb:28:in `run'
2015-08-21T17:03:43.354464+00:00 app[web.1]: config.ru:7:in `block (2 levels) in <main>'
```

**Comment by dblock** [comment]
I don't know what exception class is raised in the error above, but if it was a `Faraday::Error` it's now handled in https://github.com/dblock/slack-ruby-bot/commit/06b721fa99b05e93ab2551b0f7dbe616e106d8ec. Leaving it open until confirmed.
