### ISSUE TITLE
Disconnect not handled

### ISSUE THREAD

**Issue by dblock** [dblock/slack-ruby-bot#19]
This happened on slack-gamebot. It died.

```
2015-09-14T05:21:31.554035+00:00 app[web.1]: I, [2015-09-14T05:21:31.553943 #3]  INFO -- : Successfully connected to https://artsy.slack.com/.
2015-09-14T20:22:45.274731+00:00 app[web.1]: can't connect
2015-09-14T20:22:45.274747+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/slack-ruby-client-0.2.1/lib/slack/web/faraday/response/raise_error.rb:8:in `on_complete'
2015-09-14T20:22:45.274749+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/faraday-0.9.1/lib/faraday/response.rb:9:in `block in call'
2015-09-14T20:22:45.274751+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/faraday-0.9.1/lib/faraday/response.rb:57:in `on_complete'
2015-09-14T20:22:45.274752+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/faraday-0.9.1/lib/faraday/response.rb:8:in `call'
2015-09-14T20:22:45.274753+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/faraday-0.9.1/lib/faraday/response.rb:8:in `call'
2015-09-14T20:22:45.274755+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/faraday-0.9.1/lib/faraday/request/url_encoded.rb:15:in `call'
2015-09-14T20:22:45.274756+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/faraday-0.9.1/lib/faraday/request/multipart.rb:14:in `call'
2015-09-14T20:22:45.274757+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/faraday-0.9.1/lib/faraday/rack_builder.rb:139:in `build_response'
2015-09-14T20:22:45.274758+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/faraday-0.9.1/lib/faraday/connection.rb:377:in `run_request'
2015-09-14T20:22:45.274760+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/faraday-0.9.1/lib/faraday/connection.rb:177:in `post'
2015-09-14T20:22:45.274761+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/slack-ruby-client-0.2.1/lib/slack/web/faraday/request.rb:25:in `request'
2015-09-14T20:22:45.274762+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/slack-ruby-client-0.2.1/lib/slack/web/faraday/request.rb:10:in `post'
2015-09-14T20:22:45.274763+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/slack-ruby-client-0.2.1/lib/slack/web/api/endpoints/rtm.rb:15:in `rtm_start'
2015-09-14T20:22:45.274764+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/slack-ruby-client-0.2.1/lib/slack/real_time/client.rb:39:in `block in start!'
2015-09-14T20:22:45.274766+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/eventmachine-1.0.8/lib/eventmachine.rb:193:in `call'
2015-09-14T20:22:45.274767+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/eventmachine-1.0.8/lib/eventmachine.rb:193:in `run_machine'
2015-09-14T20:22:45.274768+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/eventmachine-1.0.8/lib/eventmachine.rb:193:in `run'
2015-09-14T20:22:45.274769+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/slack-ruby-client-0.2.1/lib/slack/real_time/client.rb:38:in `start!'
2015-09-14T20:22:45.274770+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/slack-ruby-bot-0.4.2/lib/slack-ruby-bot/app.rb:46:in `block in start!'
2015-09-14T20:22:45.274771+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/slack-ruby-bot-0.4.2/lib/slack-ruby-bot/app.rb:45:in `loop'
2015-09-14T20:22:45.274772+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/slack-ruby-bot-0.4.2/lib/slack-ruby-bot/app.rb:45:in `start!'
2015-09-14T20:22:45.274773+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/slack-ruby-bot-0.4.2/lib/slack-ruby-bot/app.rb:28:in `run'
2015-09-14T20:22:45.274775+00:00 app[web.1]: config.ru:7:in `block (2 levels) in <main>'
```

**Comment by dblock** [comment]
This is taken care of.
