### ISSUE TITLE
Provide an automatic way of handling migration_in_progress and other start errors

### ISSUE THREAD

**Issue by dblock** [dblock/slack-ruby-bot#3]
Bot doesn't survive predictable errors like `migration_in_progress`. In this case it should report an error and automatically retry or exit.

```
2015-07-17T22:39:13.867979+00:00 heroku[web.1]: State changed from starting to up
2015-07-17T22:39:14.326781+00:00 app[web.1]: I, [2015-07-17T22:39:14.326661 #3]  INFO -- : Successfully connected to https://artsy.slack.com/.
2015-07-18T16:19:10.943269+00:00 app[web.1]: migration_in_progress
2015-07-18T16:19:10.943310+00:00 app[web.1]: /app/vendor/bundle/ruby/2.1.0/gems/slack-ruby-bot-0.2.0/lib/initializers/slack/request.rb:9:in `request'
2015-07-18T16:19:10.943314+00:00 app[web.1]: /app/vendor/bundle/ruby/2.1.0/gems/slack-api-1.1.6/lib/slack/request.rb:11:in `post'
2015-07-18T16:19:10.943317+00:00 app[web.1]: /app/vendor/bundle/ruby/2.1.0/gems/slack-api-1.1.6/lib/slack/api.rb:26:in `realtime'
2015-07-18T16:19:10.943319+00:00 app[web.1]: /app/vendor/bundle/ruby/2.1.0/gems/slack-api-1.1.6/lib/slack.rb:20:in `method_missing'
2015-07-18T16:19:10.943321+00:00 app[web.1]: /app/vendor/bundle/ruby/2.1.0/gems/slack-ruby-bot-0.2.0/lib/slack-ruby-bot/app.rb:52:in `client'
2015-07-18T16:19:10.943326+00:00 app[web.1]: /app/vendor/bundle/ruby/2.1.0/gems/slack-ruby-bot-0.2.0/lib/slack-ruby-bot/app.rb:45:in `block in start!'
2015-07-18T16:19:10.943329+00:00 app[web.1]: /app/vendor/bundle/ruby/2.1.0/gems/slack-ruby-bot-0.2.0/lib/slack-ruby-bot/app.rb:44:in `loop'
2015-07-18T16:19:10.943334+00:00 app[web.1]: /app/vendor/bundle/ruby/2.1.0/gems/slack-ruby-bot-0.2.0/lib/slack-ruby-bot/app.rb:44:in `start!'
2015-07-18T16:19:10.943339+00:00 app[web.1]: /app/vendor/bundle/ruby/2.1.0/gems/slack-ruby-bot-0.2.0/lib/slack-ruby-bot/app.rb:27:in `run'
2015-07-18T16:19:10.943342+00:00 app[web.1]: config.ru:7:in `block (2 levels) in <main>'
```
And that's the beginning and the end.

See https://github.com/dblock/slack-gamebot/issues/23

**Comment by dblock** [comment]
Similar/related to https://github.com/dblock/slack-ruby-bot/issues/15.
