### ISSUE TITLE
NoMethodError: undefined method `scan' for SlackMathbot::Commands::Calculate:Class

### ISSUE THREAD

**Issue by Brandonmchu** [dblock/slack-ruby-bot#51]
scan method does not seem to work

I followed the [tutorial](https://github.com/dblock/slack-ruby-bot/blob/master/TUTORIAL.md) exactly and was able to run foreman and successfully test the bot in Slack.  Then I tried out the scan method in my calculate.rb

```
module SlackMathbot
  module Commands
    class Calculate < SlackRubyBot::Commands::Base
      scan(/hey/) do |client, data, _match|
        client.say(channel: data.channel, text: '4')
      end
    end
  end
end
```

And when trying to run foreman I get

```
19:39:54 web.1  | ! Unable to load application: NoMethodError: undefined method `scan' for SlackMathbot::Commands::Calculate:Class
19:39:54 web.1  | /Users/brandonchu/hackoff/slackbot/slack-mathbot/commands/calculate.rb:4:in `<class:Calculate>': undefined method `scan' for SlackMathbot::Commands::Calculate:Class (NoMethodError)
19:39:54 web.1  | 	from /Users/brandonchu/hackoff/slackbot/slack-mathbot/commands/calculate.rb:3:in `<module:Commands>'
19:39:54 web.1  | 	from /Users/brandonchu/hackoff/slackbot/slack-mathbot/commands/calculate.rb:2:in `<module:SlackMathbot>'
19:39:54 web.1  | 	from /Users/brandonchu/hackoff/slackbot/slack-mathbot/commands/calculate.rb:1:in `<top (required)>'
19:39:54 web.1  | 	from /Users/brandonchu/hackoff/slackbot/slack-mathbot.rb:2:in `require'
19:39:54 web.1  | 	from /Users/brandonchu/hackoff/slackbot/slack-mathbot.rb:2:in `<top (required)>'
19:39:54 web.1  | 	from config.ru:6:in `require'
19:39:54 web.1  | 	from config.ru:6:in `block in <main>'
19:39:54 web.1  | 	from /Library/Ruby/Gems/2.0.0/gems/rack-1.6.4/lib/rack/builder.rb:55:in `instance_eval'
19:39:54 web.1  | 	from /Library/Ruby/Gems/2.0.0/gems/rack-1.6.4/lib/rack/builder.rb:55:in `initialize'
19:39:54 web.1  | 	from config.ru:in `new'
19:39:54 web.1  | 	from config.ru:in `<main>'
19:39:54 web.1  | 	from /Library/Ruby/Gems/2.0.0/gems/rack-1.6.4/lib/rack/builder.rb:49:in `eval'
19:39:54 web.1  | 	from /Library/Ruby/Gems/2.0.0/gems/rack-1.6.4/lib/rack/builder.rb:49:in `new_from_string'
19:39:54 web.1  | 	from /Library/Ruby/Gems/2.0.0/gems/rack-1.6.4/lib/rack/builder.rb:40:in `parse_file'
19:39:54 web.1  | 	from /Library/Ruby/Gems/2.0.0/gems/puma-3.0.2/lib/puma/configuration.rb:310:in `load_rackup'
19:39:54 web.1  | 	from /Library/Ruby/Gems/2.0.0/gems/puma-3.0.2/lib/puma/configuration.rb:239:in `app'
19:39:54 web.1  | 	from /Library/Ruby/Gems/2.0.0/gems/puma-3.0.2/lib/puma/runner.rb:119:in `load_and_bind'
19:39:54 web.1  | 	from /Library/Ruby/Gems/2.0.0/gems/puma-3.0.2/lib/puma/single.rb:84:in `run'
19:39:54 web.1  | 	from /Library/Ruby/Gems/2.0.0/gems/puma-3.0.2/lib/puma/launcher.rb:173:in `run'
19:39:54 web.1  | 	from /Library/Ruby/Gems/2.0.0/gems/puma-3.0.2/lib/puma/cli.rb:74:in `run'
19:39:54 web.1  | 	from /Library/Ruby/Gems/2.0.0/gems/puma-3.0.2/bin/puma:10:in `<top (required)>'
19:39:54 web.1  | 	from /usr/bin/puma:23:in `load'
19:39:54 web.1  | 	from /usr/bin/puma:23:in `<main>'
19:39:54 web.1  | exited with code 1
19:39:54 system | sending SIGTERM to all processes
```

**Comment by dblock** [comment]
This was added in 0.7.0 that hasn't shipped yet, retry on HEAD?

https://github.com/dblock/slack-ruby-bot/blob/master/CHANGELOG.md
