### ISSUE TITLE
429 on boot-up

### ISSUE THREAD

**Issue by joslinm** [dblock/slack-ruby-bot#79]
As soon as I start up SlackBot, I get a 429.

I've tried to wait awhile and then start it up again, but to no avail. I work in shared working-space, so I wonder if they're blocking on the IP? The token I'm using I just made, so there's no way something else is making requests. 

If this is on your end, maybe it has to do with this requirement:

> In general we allow applications that integrate with Slack to send no more than one message per second. We allow bursts over that limit for short periods. However, if your app continues to exceed the limit over a longer period of time it will be rate limited.
-- https://api.slack.com/docs/rate-limits

At any rate, after I get this error, everything appears to be functioning normally and the bot shows itself as green. However, any command I issue to it is not going through. Simple one-word commands do not work. 

```
D, [2016-06-15T17:04:33.054462 #27834] DEBUG -- SlackRubyBot::Client#run_loop: Faye::WebSocket::API::OpenEvent
D, [2016-06-15T17:04:33.062418 #27834] DEBUG -- Slack::RealTime::Concurrency::Eventmachine::Client#parse: �{"type":"hello"}
D, [2016-06-15T17:04:33.062644 #27834] DEBUG -- SlackRubyBot::Client#run_loop: Faye::WebSocket::API::MessageEvent, {"type":"hello"}
D, [2016-06-15T17:04:33.062701 #27834] DEBUG -- SlackRubyBot::Client#dispatch: type=hello
D, [2016-06-15T17:04:33.062741 #27834] DEBUG -- Slack::RealTime::Concurrency::Eventmachine::Client#parse: �~�{"type":"reconnect_url","url":"wss://mpmulti-wy0z.slack-msgs.com/websocket/csRFV_uwRJUwuOkGn5R7iUqamO2CwMcgNrqD2dHwNenhzQYB6hWL8Vb4TyvzDkCkleyN8olff6HsvbARA2PrYQ5FeCGaPGiD1XwmhWGoX1yEIT4AgWaKgxiqIgwbG3eVpsyk_oE-hVnNFCuklzHNRzxIjDH60GvNRI16jRBcAD4="}
D, [2016-06-15T17:04:33.062793 #27834] DEBUG -- SlackRubyBot::Client#run_loop: Faye::WebSocket::API::MessageEvent, {"type":"reconnect_url","url":"wss://mpmulti-wy0z.slack-msgs.com/websocket/csRFV_uwRJUwuOkGn5R7iUqamO2CwMcgNrqD2dHwNenhzQYB6hWL8Vb4TyvzDkCkleyN8olff6HsvbARA2PrYQ5FeCGaPGiD1XwmhWGoX1yEIT4AgWaKgxiqIgwbG3eVpsyk_oE-hVnNFCuklzHNRzxIjDH60GvNRI16jRBcAD4="}
D, [2016-06-15T17:04:33.063000 #27834] DEBUG -- SlackRubyBot::Client#dispatch: type=reconnect_url, url=wss://mpmulti-wy0z.slack-msgs.com/websocket/csRFV_uwRJUwuOkGn5R7iUqamO2CwMcgNrqD2dHwNenhzQYB6hWL8Vb4TyvzDkCkleyN8olff6HsvbARA2PrYQ5FeCGaPGiD1XwmhWGoX1yEIT4AgWaKgxiqIgwbG3eVpsyk_oE-hVnNFCuklzHNRzxIjDH60GvNRI16jRBcAD4=
I, [2016-06-15T17:04:33.104998 #27834]  INFO -- Status: 429
D, [2016-06-15T17:04:33.105119 #27834] DEBUG -- response: content-type: "text/html"
transfer-encoding: "chunked"
connection: "close"
access-control-allow-origin: "*"
content-security-policy: "referrer no-referrer;"
date: "Wed, 15 Jun 2016 21:04:33 GMT"
retry-after: "60"
server: "Apache"
strict-transport-security: "max-age=31536000; includeSubDomains; preload"
x-accepted-oauth-scopes: "rtm:stream,client"
x-oauth-scopes: "identify,read,post,client,apps"
x-cache: "Error from cloudfront"
via: "1.1 7784648d4cd8093712670c85a22e6c54.cloudfront.net (CloudFront)"
x-amz-cf-id: "AZ58-9PaIS6-d7Adb4r2alODpz5CTF0BzNVxydmT7XaZkz4c5RAXxQ=="
E, [2016-06-15T17:04:33.105745 #27834] ERROR -- : the server responded with status 429 (Faraday::ClientError)
/Library/Ruby/Gems/2.0.0/gems/faraday-0.9.2/lib/faraday/response/raise_error.rb:13:in `on_complete'
/Library/Ruby/Gems/2.0.0/gems/faraday-0.9.2/lib/faraday/response.rb:9:in `block in call'
/Library/Ruby/Gems/2.0.0/gems/faraday-0.9.2/lib/faraday/response.rb:57:in `on_complete'
/Library/Ruby/Gems/2.0.0/gems/faraday-0.9.2/lib/faraday/response.rb:8:in `call'
/Library/Ruby/Gems/2.0.0/gems/faraday_middleware-0.9.2/lib/faraday_middleware/response_middleware.rb:30:in `call'
/Library/Ruby/Gems/2.0.0/gems/faraday-0.9.2/lib/faraday/response.rb:8:in `call'
/Library/Ruby/Gems/2.0.0/gems/faraday-0.9.2/lib/faraday/response.rb:8:in `call'
/Library/Ruby/Gems/2.0.0/gems/faraday-0.9.2/lib/faraday/request/url_encoded.rb:15:in `call'
/Library/Ruby/Gems/2.0.0/gems/faraday-0.9.2/lib/faraday/request/multipart.rb:14:in `call'
/Library/Ruby/Gems/2.0.0/gems/faraday-0.9.2/lib/faraday/rack_builder.rb:139:in `build_response'
/Library/Ruby/Gems/2.0.0/gems/faraday-0.9.2/lib/faraday/connection.rb:377:in `run_request'
/Library/Ruby/Gems/2.0.0/gems/faraday-0.9.2/lib/faraday/connection.rb:177:in `post'
/Library/Ruby/Gems/2.0.0/gems/slack-ruby-client-0.7.4/lib/slack/web/faraday/request.rb:25:in `request'
/Library/Ruby/Gems/2.0.0/gems/slack-ruby-client-0.7.4/lib/slack/web/faraday/request.rb:10:in `post'
/Library/Ruby/Gems/2.0.0/gems/slack-ruby-client-0.7.4/lib/slack/web/api/endpoints/rtm.rb:21:in `rtm_start'
/Library/Ruby/Gems/2.0.0/gems/slack-ruby-client-0.7.4/lib/slack/real_time/client.rb:110:in `build_socket'
/Library/Ruby/Gems/2.0.0/gems/slack-ruby-client-0.7.4/lib/slack/real_time/client.rb:50:in `start!'
/Library/Ruby/Gems/2.0.0/gems/slack-ruby-bot-0.8.0/lib/slack-ruby-bot/server.rb:37:in `start!'
/Library/Ruby/Gems/2.0.0/gems/slack-ruby-bot-0.8.0/lib/slack-ruby-bot/server.rb:29:in `block (2 levels) in run'
/Library/Ruby/Gems/2.0.0/gems/slack-ruby-bot-0.8.0/lib/slack-ruby-bot/server.rb:63:in `handle_exceptions'
/Library/Ruby/Gems/2.0.0/gems/slack-ruby-bot-0.8.0/lib/slack-ruby-bot/server.rb:27:in `block in run'
/Library/Ruby/Gems/2.0.0/gems/slack-ruby-bot-0.8.0/lib/slack-ruby-bot/server.rb:26:in `loop'
/Library/Ruby/Gems/2.0.0/gems/slack-ruby-bot-0.8.0/lib/slack-ruby-bot/server.rb:26:in `run'
/Library/Ruby/Gems/2.0.0/gems/slack-ruby-bot-0.8.0/lib/slack-ruby-bot/bot.rb:6:in `run'
config/master-config.ru:10:in `block (2 levels) in <main>'
SLACKBOT ERROR the server responded with status 429
```

**Comment by dblock** [comment]
There seems to be a successful connection above, then you get a 429. Are you starting the bot in a loop again and again? Check what's in `master-config.ru`, I bet there's code like `loop do { ...start_async }`, which is incorrect.

**Comment by joslinm** [comment]
No my friend -- that's actually what I checked first too. I will investigate more in that area, but here's the contents of my `master-config.ru`:

```
###########
# config.ru
#
require_relative '../src/master/orchestrator'
require_relative '../src/master/slack'

# You
Thread.new do
  begin
    SlackBot.configure
    SlackBot.run
  rescue Exception =>e
    STDERR.puts "SLACKBOT ERROR #{ e }"
  end
end

Thread.new do
  begin
    SQSListener.listen
  rescue Exception => e
    STDERR.puts "SQS LISTENER ERROR #{ e }"
  end
end

run Orchestrator
```

Here's what my Slack code looks like:

```
# Sends and receives messages from Slack

require 'slack-ruby-bot'

class SlackBot < SlackRubyBot::Bot

  command 'ping' do |client, data, match|
    puts "GOT PING COMMAND!"
    client.say(text: 'pong', :channel => data.channel)
  end

  match /^deploy (?<stage>\w+) (?<type>\w+)\?$/ do |client, data, match|
    stage = match[:stage]
    type  = match[:type]

    if type =~ /api/i
      puts("Depoying API!")
      APIDeployer.new(stage.to_sym).deploy
    end
  end


  def self.configure
    puts "Configuring??"
    Slack.configure do |config|
      config.token = ENV['SLACK_API_TOKEN']
      fail "NO TOKEN" unless config.token
    end
  end

  def self.say(msg)
    configure

    client = Slack::Web::Client.new
    client.auth_test
    client.chat_postMessage(channel: '#dev-console', text: msg, as_user: true)
  end

end
```

**Comment by dblock** [comment]
I don't see anything wrong, take an example from this project and try to run it with your token, maybe the simplest one, https://github.com/dblock/slack-ruby-bot/tree/master/examples/minimal.

Then stick a `puts` into /Library/Ruby/Gems/2.0.0/gems/slack-ruby-bot-0.8.0/lib/slack-ruby-bot/server.rb and see if it is looping over a start. 

Reopen another bug for the celluloid problem, I feel like I've seen this, but google didn't surface anything. What's the OS, too?

**Comment by joslinm** [comment]
The OS is OSX. You're right -- it must be on my end because the minimal pong bot is working just fine with the token. I'm seeing tons of requests with my code. I will attempt to trace it and get to bottom of it, but it's safe to say this isn't a bug in `slack-ruby-bot`.

**Comment by dblock** [comment]
@joslinm I am going to close this, do let us know when you found the issue.
