### ISSUE TITLE
rspec fail due to vcr dependency.

### ISSUE THREAD

**Issue by Nictrasavios** [dblock/slack-ruby-bot#82]
Command:
`$ rspec spec`

Ouput:
```
I, [2016-06-23T21:39:40.297875 #28330]  INFO -- : Celluloid 0.17.3 is running in BACKPORTED mode. [ http://git.io/vJf3J ]
/home/nictrasavios/.rvm/gems/ruby-2.3.1/gems/slack-ruby-bot-0.8.0/lib/slack-ruby-bot/rspec/support/vcr.rb:1:in `require': cannot load such file -- vcr (LoadError)
	from /home/nictrasavios/.rvm/gems/ruby-2.3.1/gems/slack-ruby-bot-0.8.0/lib/slack-ruby-bot/rspec/support/vcr.rb:1:in `<top (required)>'
	from /home/nictrasavios/.rvm/gems/ruby-2.3.1/gems/slack-ruby-bot-0.8.0/lib/slack-ruby-bot/rspec.rb:11:in `require'
	from /home/nictrasavios/.rvm/gems/ruby-2.3.1/gems/slack-ruby-bot-0.8.0/lib/slack-ruby-bot/rspec.rb:11:in `block in <top (required)>'
	from /home/nictrasavios/.rvm/gems/ruby-2.3.1/gems/slack-ruby-bot-0.8.0/lib/slack-ruby-bot/rspec.rb:10:in `each'
	from /home/nictrasavios/.rvm/gems/ruby-2.3.1/gems/slack-ruby-bot-0.8.0/lib/slack-ruby-bot/rspec.rb:10:in `<top (required)>'
	from /media/Data/Development/AscensionLabs/ascensionbot/spec/spec_helper.rb:3:in `require'
	from /media/Data/Development/AscensionLabs/ascensionbot/spec/spec_helper.rb:3:in `<top (required)>'
	from /media/Data/Development/AscensionLabs/ascensionbot/spec/ascensionbot_spec.rb:1:in `require'
	from /media/Data/Development/AscensionLabs/ascensionbot/spec/ascensionbot_spec.rb:1:in `<top (required)>'
	from /home/nictrasavios/.rvm/gems/ruby-2.3.1/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1361:in `load'
	from /home/nictrasavios/.rvm/gems/ruby-2.3.1/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1361:in `block in load_spec_files'
	from /home/nictrasavios/.rvm/gems/ruby-2.3.1/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1359:in `each'
	from /home/nictrasavios/.rvm/gems/ruby-2.3.1/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1359:in `load_spec_files'
	from /home/nictrasavios/.rvm/gems/ruby-2.3.1/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:106:in `setup'
	from /home/nictrasavios/.rvm/gems/ruby-2.3.1/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:92:in `run'
	from /home/nictrasavios/.rvm/gems/ruby-2.3.1/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:78:in `run'
	from /home/nictrasavios/.rvm/gems/ruby-2.3.1/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:45:in `invoke'
	from /home/nictrasavios/.rvm/gems/ruby-2.3.1/gems/rspec-core-3.4.4/exe/rspec:4:in `<top (required)>'
	from /home/nictrasavios/.rvm/gems/ruby-2.3.1/bin/rspec:23:in `load'
	from /home/nictrasavios/.rvm/gems/ruby-2.3.1/bin/rspec:23:in `<main>'
	from /home/nictrasavios/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
	from /home/nictrasavios/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by dblock** [comment]
Did you `bundle install` first?

**Comment by Nictrasavios** [comment]
Absolutely, I even tried manually installing just vcr.

On Saturday, 25 June 2016, Daniel Doubrovkine (dB.) @dblockdotorg <
notifications@github.com> wrote:

> Did you bundle install first?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/dblock/slack-ruby-bot/issues/82#issuecomment-228521251>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AFIumtOAs4pyx1ajMAURHfDpo9Qpk97_ks5qPN8fgaJpZM4I9Xv8>
> .
>


-- 
Regards,
Joseph Harrietha

**Comment by dblock** [comment]
And you're running `bundle exec rspec spec`? I don't see this problem obviously ;)

**Comment by Nictrasavios** [comment]
I can't actually remember, and I deleted all my project files. I've moved
on to using slack-ruby-bot-server, and I have a new set of rspec and
compilation errors... *sigh*.

Regards,
Joseph Harrietha

**Comment by dblock** [comment]
I am going to close this. Looking at the stack this is in your bot, I thought it was here. You just need to add `vcr` as a dependency in Gemfile. Look at the working bot examples, such as https://github.com/dblock/slack-market.
